### PR TITLE
sb service improvement

### PR DESCRIPTION
**Pull request by dmarrazzo**
- removed useless copy of the jar
- switch to UBI

### CODE REVIEW

**Comment by rafaeltuelho** [comment]
Hi @dmarrazzo 
Did you have the opportunity to test this change in your OCP Cluster?  I mean does the service runs ok with the UBI image?
I'll try to test on my end tomorrow before I merge your PR.

**Comment by dmarrazzo** [comment]
Yes tested on my side

**Comment by dmarrazzo** [comment]
Hi @rafaeltuelho I have just found a strange behavior, please park this PR while investigating.

**Comment by rafaeltuelho** [comment]
> Hi @rafaeltuelho I have just found a strange behavior, please park this PR while investigating.

sure! I'll try to test it on my side too.

**Comment by dmarrazzo** [comment]
Hi @rafaeltuelho , I did further clean up and tuning.
Now it should be fine.

**Comment by rafaeltuelho** [comment]
Thank you @dmarrazzo!

**Pull request merged**
